// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { AccountInLeague, AccountInLeagueTableId } from "./tables/AccountInLeague.sol";
import { Organiser, OrganiserTableId } from "./tables/Organiser.sol";
