// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IJoinSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IJoinSystem {
  function League_JoinSystem_addLeague(address account) external;
}
