// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ILeagueManagementSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ILeagueManagementSystem {
  function MY_NAMESPACE_LeagueManagement_addLeagueMember(address account) external;
}
